# workflow name
name: SimpleCI

# trigger
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:
  

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: action/checkout@v2
        - name: Run a one-line script
          run: echo Hello, World!
          
        - name: Run a multiple line script
          run: 
            echo Add other actions to build,
            echo test, and deploy your project
          
        

    
